# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/nick/Documents/FPGA_PONG/embedded_pong/embedded_pong.srcs/sources_1/zybo_lab_5.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_pixel_pusher_0_0/design_1_pixel_pusher_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_pixel_pusher_0_0 || ORIG_REF_NAME==design_1_pixel_pusher_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_vga_ctrl_0_0/design_1_vga_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_vga_ctrl_0_0 || ORIG_REF_NAME==design_1_vga_ctrl_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clock_div_25_0_0/design_1_clock_div_25_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clock_div_25_0_0 || ORIG_REF_NAME==design_1_clock_div_25_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_controller_0_0/design_1_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_controller_0_0 || ORIG_REF_NAME==design_1_controller_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_debounce_0_0/design_1_debounce_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_debounce_0_0 || ORIG_REF_NAME==design_1_debounce_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_debounce_1_0/design_1_debounce_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_debounce_1_0 || ORIG_REF_NAME==design_1_debounce_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_debounce_2_0/design_1_debounce_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_debounce_2_0 || ORIG_REF_NAME==design_1_debounce_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_debounce_3_0/design_1_debounce_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_debounce_3_0 || ORIG_REF_NAME==design_1_debounce_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ssd_out_0_0/design_1_ssd_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ssd_out_0_0 || ORIG_REF_NAME==design_1_ssd_out_0_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
